In [1]:
'''
This is Homework 4 for AMATH 581
Tianbo Zhang 1938501
'''
import numpy as np
from scipy.sparse import spdiags

# Parameters
m = 8  # Grid size per dimension
n = m * m  # Total number of grid points
L = 10  # Domain size
dx = (2 * L) / m  # Grid spacing

# Base vectors for diagonals
ones = np.ones(n)
zeros = np.zeros(n)

# Periodic wrap diagonals: farthest connections
periodic_shift_m1 = np.zeros(n)
periodic_shift_p1 = np.ones(n)
periodic_shift_m1[m-1::m] = 1
periodic_shift_p1[m-1::m] = 0
periodic_shift_m1_re = np.concatenate((periodic_shift_m1[-1:], periodic_shift_m1[:-1]))
periodic_shift_p1_re = np.concatenate((periodic_shift_p1[-1:], periodic_shift_p1[:-1]))


# Construct derivative matrix A1 (Laplacian)
diagonals_a = [-4 * ones, periodic_shift_p1, periodic_shift_p1_re, 
               periodic_shift_m1_re, periodic_shift_m1, 
               ones, ones, ones, ones]
offsets_a = [0, -1, 1, -(m - 1), m - 1, m, -m, -(n - m), (n - m)]

A1 = spdiags(diagonals_a, offsets_a, n, n).toarray() / dx**2

# Construct derivative matrix A2 (x-derivative)
diagonals_b = [ones, -ones, -ones, ones]
offsets_b = [m, -m, n - m, -(n - m)]

A2 = spdiags(diagonals_b, offsets_b, n, n).toarray() / (2 * dx)

# Construct derivative matrix A3 (y-derivative)
diagonals_c = [periodic_shift_m1_re, -periodic_shift_m1, -periodic_shift_p1, periodic_shift_p1_re]
offsets_c = [-(m - 1), m - 1, -1, 1]

A3 = spdiags(diagonals_c, offsets_c, n, n).toarray() / (2 * dx)

In [2]:
A1

array([[-0.64,  0.16,  0.  , ...,  0.  ,  0.  ,  0.  ],
       [ 0.16, -0.64,  0.16, ...,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.16, -0.64, ...,  0.  ,  0.  ,  0.  ],
       ...,
       [ 0.  ,  0.  ,  0.  , ..., -0.64,  0.16,  0.  ],
       [ 0.  ,  0.  ,  0.  , ...,  0.16, -0.64,  0.16],
       [ 0.  ,  0.  ,  0.  , ...,  0.  ,  0.16, -0.64]])

In [3]:
A2

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [4]:
A3

array([[ 0. ,  0.2,  0. , ...,  0. ,  0. ,  0. ],
       [-0.2,  0. ,  0.2, ...,  0. ,  0. ,  0. ],
       [ 0. , -0.2,  0. , ...,  0. ,  0. ,  0. ],
       ...,
       [ 0. ,  0. ,  0. , ...,  0. ,  0.2,  0. ],
       [ 0. ,  0. ,  0. , ..., -0.2,  0. ,  0.2],
       [ 0. ,  0. ,  0. , ...,  0. , -0.2,  0. ]])